import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import RootLayoutThatConfiguresAmplifyOnClient from "./rootLayoutThatConfigureAmplifyOnClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayoutThatConfiguresAmplifyOnClient>
        {children}
        </RootLayoutThatConfiguresAmplifyOnClient>
        </body>
    </html>
  );
}

// import "./app.css";
// import outputs from '@/amplify_outputs.json';
// import { Amplify } from 'aws-amplify';

// Amplify.configure(outputs, {
//   ssr: true // required when using Amplify with Next.js
// });

// export default function RootLayoutThatConfiguresAmplifyOnTheClient({
//   children
// }: {
//   children: React.ReactNode;
// }) {
//   return children;
// }
